#!/bin/bash
CUDA_VISIBLE_DEVICES=0 python main.py \
    --do_train \
    --scene pegasus_xsum_generation \
    --use_logit True \
    --report_to tensorboard \
    --seed 2022 \
    --smooth 0.1 \
    --trainer rl \
    --learning_rate 0.000002 \
    --num_train_epochs 60 \
    --max_grad_norm 1 \
    --print_every 8000 \
    --save_every 8000 \
    --eval_steps 4000 \
    --per_device_train_batch_size 1 \
    --gradient_accumulation_steps 8 \
    --per_device_eval_batch_size 4 \
    --length_normalize_4_rl True \
    --training_length_penalty 1 \
    --train_dir static_data/xsum/xsum_train.tsv \
    --eval_dir static_data/xsum/xsum_valid.tsv \
    --model 'google/pegasus-xsum' \
    --recover model_output/xsum_base_model \
    --exp_name demo_xsum \
    --rewards 'rouge' \
    --rouge_type 12l \
    --eval_metrics rouges,rouge \
    --kd_inputs_worst True \
    --seq_decode_model pegasus \
    --rl_weight 2 \
    --sample_num 63 \
    --mask_rate 0.4 \
