#!/bin/bash
CUDA_VISIBLE_DEVICES=0 python main.py \
    --do_train \
    --scene bart_cnndm_generation \
    --use_logit True \
    --report_to tensorboard \
    --seed 2022 \
    --smooth 0.1 \
    --trainer rl \
    --save_steps 10000000 \
    --learning_rate 0.000001 \
    --num_train_epochs 60 \
    --max_grad_norm 1 \
    --print_every 1000 \
    --save_every 4000 \
    --eval_steps 2000 \
    --per_device_train_batch_size 1 \
    --gradient_accumulation_steps 8 \
    --per_device_eval_batch_size 16 \
    --length_normalize_4_rl True \
    --training_length_penalty 1 \
    --train_dir static_data/cnndm/cnndm_train.tsv \
    --eval_dir static_data/cnndm/cnndm_valid.tsv \
    --cand_pos_remove_sp_tk True \
    --recover model_output/cnndm_base_model \
    --exp_name demo_cnndm \
    --rewards 'rouge' \
    --rouge_type 12l \
    --reward_type rouges \
    --rl_weight 20 \
    --sample_num 63 \
    --mask_rate 0.4 \
    --kd_inputs_worst True \
    --eval_metrics rouges,rouge \
    --seq_decode_model bart \
